site_name: SharpLog
site_url: https://sharplog.marvin-fuchs.de/
repo_url: https://github.com/habetuz/SharpLog/
edit_uri: ""
theme:
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - content.code.annotate
  name: material
  palette:
    scheme: slate
    primary: deep orange
    accent: orange
  font:
    text: Montserrat
    code: Roboto Mono
markdown_extensions:
  - admonition
  - toc:
      permalink: true
      toc_depth: 3
  - meta
  - pymdownx.details
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search
extra_css:
  - stylesheets/extra.css
